import wildstrawberry from "./images/plantPhotos/wildstrawberry.png";

export default [
  //Full sun, wet soil
  {
    name: "Wild Strawberry",
    bloomTime: "Spring",
    color: "White",
    height: "Ground cover",
    sun: ["Full sun", "Partial sun", "Full shade"],
    soiltype: ["Wet", "Medium", "Dry"],
    photo: "wildstrawberry",
  },
  {
    name: "Golden Alexanders",
    bloomTime: "Spring",
    color: "Yellow",
    height: "Short",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
    photo: "goldenalexanders",
  },
  {
    name: "Blue Wild Indigo",
    bloomTime: "Spring",
    color: "Blue",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
    photo: "bluewildindigo",
  },
  {
    name: "Early Sunflower",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
    photo: "earlysunflower",
  },
  {
    name: "Swamp Milkweed",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
    photo: "swampmilkweed",
  },
  {
    name: "Purple Coneflower",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
    photo: "purpleconeflower",
  },
  {
    name: "Wild Bergamot",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium", "Dry"],
    photo: "wildbergamot",
  },
  {
    name: "Blue Vervain",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
    photo: "bluevervain",
  },
  {
    name: "Common Ironweed",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
    photo: "commonironweed",
  },
  {
    name: "Prairie Blazing Star",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
    photo: "prairieblazingstar",
  },
  {
    name: "Rose Mallow",
    bloomTime: "Summer",
    color: "White",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
    photo: "rosemallow",
  },
  {
    name: "Cardinal Flower",
    bloomTime: "Summer",
    color: "Red",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
    photo: "cardinalflower",
  },
  {
    name: "Joe Pye Weed",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
    photo: "joepyeweed",
  },
  {
    name: "Stiff Goldenrod",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
    photo: "stiffgoldenrod",
  },
  {
    name: "Sneezeweed",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
    photo: "sneezeweed",
  },
  {
    name: "New England Aster",
    bloomTime: "Fall",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
    photo: "newenglandaster",
  },
  //Full sun, medium soil
  {
    name: "Prairie Phlox",
    bloomTime: "Spring",
    color: "Pink",
    height: "Short",
    sun: ["Full sun"],
    soiltype: ["Medium"],
    photo: "prairiephlox",
  },
  {
    name: "Ozark Bluestar",
    bloomTime: "Spring",
    color: "White",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium"],
    photo: "ozarkbluestar",
  },
  {
    name: "Foxglove Beardtongue",
    bloomTime: "Spring",
    color: "White",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium"],
    photo: "foxglovebeardtongue",
  },
  {
    name: "Showy Milkweed",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
    photo: "showymilkweed",
  },
  {
    name: "Whorled Milkweed",
    bloomTime: "Summer",
    color: "White",
    height: "Short",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
    photo: "whorledmilkweed",
  },
  {
    name: "Butterfly Milkweed",
    bloomTime: "Summer",
    color: "Orange",
    height: "Short",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
    photo: "butterflymilkweed",
  },
  {
    name: "Anise Hyssop",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium"],
    photo: "anisehyssop",
  },
  {
    name: "Purple Prairie Clover",
    bloomTime: "Summer",
    color: "Purple",
    height: "Short",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
    photo: "purpleprairieclover",
  },
  {
    name: "Tall Coreopsis",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Tall",
    sun: ["Full sun"],
    soiltype: ["Medium"],
    photo: "tallcoreopsis",
  },
  {
    name: "Purple Giant Hyssop",
    bloomTime: "Summer",
    color: "White",
    height: "Tall",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium"],
    photo: "purplegianthyssop",
  },
  {
    name: "Wild Petunia",
    bloomTime: "Summer",
    color: "Purple",
    height: "Short",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
    photo: "wildpetunia",
  },
  {
    name: "Gray Headed Coneflower",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium"],
    photo: "grayheadedconeflower",
  },
  {
    name: "Pitcher Sage",
    bloomTime: "Fall",
    color: "Blue",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium", "Dry"],
    photo: "pitchersage",
  },
  {
    name: "Showy Goldenrod",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
    photo: "showygoldenrod",
  },
  {
    name: "Brown Eyed Susan",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun"],
    soiltype: ["Medium"],
    photo: "browneyedsusan",
  },

  //Full sun, dry soil
  {
    name: "Prairie Pussytoes",
    bloomTime: "Spring",
    color: "White",
    height: "Ground cover",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
    photo: "prairiepussytoes",
  },
  {
    name: "White Wild Indigo",
    bloomTime: "Spring",
    color: "White",
    height: "Medium",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
    photo: "whitewildindigo",
  },
  {
    name: "Large-flowered Beardtongue",
    bloomTime: "Spring",
    color: "White",
    height: "Medium",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
    photo: "largefloweredbeardtongue",
  },
  {
    name: "Lance-leaf Coreopsis",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun"],
    soiltype: ["Dry"],
    photo: "lanceleafcoreopsis",
  },
  {
    name: "Pale Purple Coneflower",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
    photo: "palepurpleconeflower",
  },
  {
    name: "Purple Poppy Mallow",
    bloomTime: "Summer",
    color: "Purple",
    height: "Grounc cover",
    sun: ["Full sun"],
    soiltype: ["Dry"],
    photo: "purplepoppymallow",
  },
  {
    name: "Button Blazing Star",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
    photo: "buttonblazingstar",
  },
  {
    name: "Hoary Vervain",
    bloomTime: "Summer",
    color: "Purple",
    height: "Short",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
    photo: "hoaryvervain",
  },
  {
    name: "Aromatic Aster",
    bloomTime: "Fall",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun"],
    soiltype: ["Dry"],
    photo: "aromaticaster",
  },
  {
    name: "Showy Sunflower",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Tall",
    sun: ["Full sun"],
    soiltype: ["Dry"],
    photo: "showysunflower",
  },
  //Partial sun, Wet soil
  {
    name: "Calico Aster",
    bloomTime: "Fall",
    color: "White",
    height: "Medium",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Wet", "Medium", "Dry"],
    photo: "calicoaster",
  },
  {
    name: "Tall Bellflower",
    bloomTime: "Fall",
    color: "Blue",
    height: "Medium",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Wet", "Medium"],
    photo: "tallbellflower",
  },
  {
    name: "Blue Mistflower",
    bloomTime: "Fall",
    color: "Blue",
    height: "Short",
    sun: ["Partial sun"],
    soiltype: ["Wet"],
    photo: "bluemistflower",
  },
  //Partial sun, Medium soil
  {
    name: "Wild Geranium",
    bloomTime: "Spring",
    color: "Pink",
    height: "Short",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Medium", "Dry"],
    photo: "wildgeranium",
  },
  {
    name: "Common Milkweed",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Partial sun"],
    soiltype: ["Medium", "Dry"],
    photo: "commonmilkweed",
  },
  {
    name: "Smooth Wild Petunia",
    bloomTime: "Summer",
    color: "Purple",
    height: "Short",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Medium"],
    photo: "smoothwildpetunia",
  },
  {
    name: "Wild Blue Phlox",
    bloomTime: "Summer",
    color: "Blue",
    height: "Short",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Medium", "Dry"],
    photo: "wildbluephlox",
  },
  {
    name: "Zig Zag Goldenrod",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Short",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Medium", "Dry"],
    photo: "zigzaggoldenrod",
  },
  {
    name: "Drummond's Aster",
    bloomTime: "Fall",
    color: "Blue",
    height: "Medium",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Medium", "Dry", "Wet"],
    photo: "drummondsaster",
  },
  {
    name: "Great Blue Lobelia",
    bloomTime: "Fall",
    color: "Blue",
    height: "Medium",
    sun: ["Partial sun"],
    soiltype: ["Medium"],
    photo: "greatbluelobelia",
  },
  //Partial sun, Dry soil
  {
    name: "Columbine",
    bloomTime: "Spring",
    color: "Red",
    height: "Medium",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Dry", "Medium"],
    photo: "columbine",
  },
  {
    name: "Tall Thimbleweed",
    bloomTime: "Spring",
    color: "Pink",
    height: "Short",
    sun: ["Partial sun"],
    soiltype: ["Dry"],
    photo: "tallthimbleweed",
  },
  {
    name: "Sky Blue Aster",
    bloomTime: "Fall",
    color: "Blue",
    height: "Medium",
    sun: ["Partial sun"],
    soiltype: ["Dry"],
    photo: "skyblueaster",
  },
  //Full shade, Wet soil
  {
    name: "Virginia Bluebells",
    bloomTime: "Spring",
    color: "Blue",
    height: "Short",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium"],
    photo: "virginiabluebells",
  },
  {
    name: "Hairy Wood Mint",
    bloomTime: "Summer",
    color: "White",
    height: "Short",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium"],
    photo: "hairywoodmint",
  },
  {
    name: "Sweet Joe Pye Weed",
    bloomTime: "Summer",
    color: "Pink",
    height: "Tall",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium", "Dry"],
    photo: "sweetjoepyeweed",
  },
  {
    name: "Wingstem",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Tall",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium"],
    photo: "wingstem",
  },
  {
    name: "Poke Milkweed",
    bloomTime: "Summer",
    color: "White",
    height: "Medium",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium", "Dry"],
    photo: "pokemilkweed",
  },
  {
    name: "Wild Golden Glow",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Tall",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium"],
    photo: "wildgoldenglow",
  },
  //Full shade, medium soil
  {
    name: "Hairy Beardtongue",
    bloomTime: "Spring",
    color: "White",
    height: "Medium",
    sun: ["Full shade"],
    soiltype: ["Medium", "Dry"],
    photo: "hairybeardtongue",
  },
  //Full shade, dry soil
  {
    name: "Jacob's Ladder",
    bloomTime: "Spring",
    color: "White",
    height: "Short",
    sun: ["Full shade"],
    soiltype: ["Dry", "Medium", "Wet"],
    photo: "jacobsladder",
  },
];
