export default [
  //Full sun, wet soil
  {
    name: "Wild Strawberry",
    bloomTime: "Spring",
    color: "White",
    height: "Ground cover",
    sun: ["Full sun", "Partial sun", "Full shade"],
    soiltype: ["Wet", "Medium", "Dry"],
  },
  {
    name: "Golden Alexanders",
    bloomTime: "Spring",
    color: "Yellow",
    height: "Short",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
  },
  {
    name: "Blue Wild Indigo",
    bloomTime: "Spring",
    color: "Blue",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
  },
  {
    name: "Early Sunflower",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
  },
  {
    name: "Swamp Milkweed",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
  },
  {
    name: "Purple Coneflower",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
  },
  {
    name: "Wild Bergamot",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium", "Dry"],
  },
  {
    name: "Blue Vervain",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
  },
  {
    name: "Common Ironweed",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
  },
  {
    name: "Prairie Blazing Star",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
  },
  {
    name: "Rose Mallow",
    bloomTime: "Summer",
    color: "White",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
  },
  {
    name: "Cardinal Flower",
    bloomTime: "Summer",
    color: "Red",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
  },
  {
    name: "Joe Pye Weed",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
  },
  {
    name: "Stiff Goldenrod",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
  },
  {
    name: "Sneezeweed",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet"],
  },
  {
    name: "New England Aster",
    bloomTime: "Fall",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Wet", "Medium"],
  },
  //Full sun, medium soil
  {
    name: "Prairie Phlox",
    bloomTime: "Spring",
    color: "Pink",
    height: "Short",
    sun: ["Full sun"],
    soiltype: ["Medium"],
  },
  {
    name: "Ozark Bluestar",
    bloomTime: "Spring",
    color: "White",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium"],
  },
  {
    name: "Foxglove Beardtongue",
    bloomTime: "Spring",
    color: "White",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium"],
  },
  {
    name: "Showy Milkweed",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Whorled Milkweed",
    bloomTime: "Summer",
    color: "White",
    height: "Short",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Butterfly Milkweed",
    bloomTime: "Summer",
    color: "Orange",
    height: "Short",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Anise Hyssop",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium"],
  },
  {
    name: "Purple Prairie Clover",
    bloomTime: "Summer",
    color: "Purple",
    height: "Short",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Tall Coreopsis",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Tall",
    sun: ["Full sun"],
    soiltype: ["Medium"],
  },
  {
    name: "Purple Giant Hyssop",
    bloomTime: "Summer",
    color: "White",
    height: "Tall",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium"],
  },
  {
    name: "Wild Petunia",
    bloomTime: "Summer",
    color: "Purple",
    height: "Short",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Gray Headed Coneflower",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium"],
  },
  {
    name: "Pitcher Sage",
    bloomTime: "Fall",
    color: "Blue",
    height: "Medium",
    sun: ["Full sun", "Partial sun"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Showy Goldenrod",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Brown Eyed Susan",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun"],
    soiltype: ["Medium"],
  },

  //Full sun, dry soil
  {
    name: "Prairie Pussytoes",
    bloomTime: "Spring",
    color: "White",
    height: "Ground cover",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
  },
  {
    name: "White Wild Indigo",
    bloomTime: "Spring",
    color: "White",
    height: "Medium",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
  },
  {
    name: "Large-flowered Beardtongue",
    bloomTime: "Spring",
    color: "White",
    height: "Medium",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
  },
  {
    name: "Lance-leaf Coreopsis",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Medium",
    sun: ["Full sun"],
    soiltype: ["Dry"],
  },
  {
    name: "Pale Purple Coneflower",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
  },
  {
    name: "Purple Poppy Mallow",
    bloomTime: "Summer",
    color: "Purple",
    height: "Grounc cover",
    sun: ["Full sun"],
    soiltype: ["Dry"],
  },
  {
    name: "Button Blazing Star",
    bloomTime: "Summer",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
  },
  {
    name: "Hoary Vervain",
    bloomTime: "Summer",
    color: "Purple",
    height: "Short",
    sun: ["Full sun", "Partial Sun"],
    soiltype: ["Dry"],
  },
  {
    name: "Aromatic Aster",
    bloomTime: "Fall",
    color: "Purple",
    height: "Medium",
    sun: ["Full sun"],
    soiltype: ["Dry"],
  },
  {
    name: "Showy Sunflower",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Tall",
    sun: ["Full sun"],
    soiltype: ["Dry"],
  },
  //Partial sun, Wet soil
  {
    name: "Calico Aster",
    bloomTime: "Fall",
    color: "White",
    height: "Medium",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Wet", "Medium", "Dry"],
  },
  {
    name: "Tall Bellflower",
    bloomTime: "Fall",
    color: "Blue",
    height: "Medium",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Wet", "Medium"],
  },
  {
    name: "Blue Mistflower",
    bloomTime: "Fall",
    color: "Blue",
    height: "Short",
    sun: ["Partial sun"],
    soiltype: ["Wet"],
  },
  //Partial sun, Medium soil
  {
    name: "Wild Geranium",
    bloomTime: "Spring",
    color: "Pink",
    height: "Short",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Common Milkweed",
    bloomTime: "Summer",
    color: "Pink",
    height: "Medium",
    sun: ["Partial sun"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Smooth Wild Petunia",
    bloomTime: "Summer",
    color: "Purple",
    height: "Short",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Medium"],
  },
  {
    name: "Wild Blue Phlox",
    bloomTime: "Summer",
    color: "Blue",
    height: "Short",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Zig Zag Goldenrod",
    bloomTime: "Fall",
    color: "Yellow",
    height: "Short",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Medium", "Dry"],
  },
  {
    name: "Drummond's Aster",
    bloomTime: "Fall",
    color: "Blue",
    height: "Medium",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Medium", "Dry", "Wet"],
  },
  {
    name: "Great Blue Lobelia",
    bloomTime: "Fall",
    color: "Blue",
    height: "Medium",
    sun: ["Partial sun"],
    soiltype: ["Medium"],
  },
  //Partial sun, Dry soil
  {
    name: "Columbine",
    bloomTime: "Spring",
    color: "Red",
    height: "Medium",
    sun: ["Partial sun", "Full shade"],
    soiltype: ["Dry", "Medium"],
  },
  {
    name: "Tall Thimbleweed",
    bloomTime: "Spring",
    color: "Pink",
    height: "Short",
    sun: ["Partial sun"],
    soiltype: ["Dry"],
  },
  {
    name: "Sky Blue Aster",
    bloomTime: "Fall",
    color: "Blue",
    height: "Medium",
    sun: ["Partial sun"],
    soiltype: ["Dry"],
  },
  //Full shade, Wet soil
  {
    name: "Virginia Bluebells",
    bloomTime: "Spring",
    color: "Blue",
    height: "Short",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium"],
  },
  {
    name: "Hairy Wood Mint",
    bloomTime: "Summer",
    color: "White",
    height: "Short",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium"],
  },
  {
    name: "Sweet Joe Pye Weed",
    bloomTime: "Summer",
    color: "Pink",
    height: "Tall",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium", "Dry"],
  },
  {
    name: "Wingstem",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Tall",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium"],
  },
  {
    name: "Poke Milkweed",
    bloomTime: "Summer",
    color: "White",
    height: "Medium",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium", "Dry"],
  },
  {
    name: "Wild Golden Glow",
    bloomTime: "Summer",
    color: "Yellow",
    height: "Tall",
    sun: ["Full shade"],
    soiltype: ["Wet", "Medium"],
  },
  //Full shade, medium soil
  {
    name: "Hairy Beardtongue",
    bloomTime: "Spring",
    color: "White",
    height: "Medium",
    sun: ["Full shade"],
    soiltype: ["Medium", "Dry"],
  },
  //Full shade, dry soil
  {
    name: "Jacob's Ladder",
    bloomTime: "Spring",
    color: "White",
    height: "Short",
    sun: ["Full shade"],
    soiltype: ["Dry", "Medium", "Wet"],
  },
];
